name: Playwright STG PROD Pipeline

on:
  workflow_dispatch:

jobs:
  stg-test:
    name: STG Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run STG Tests
        run: npx playwright test tests/login.spec.ts --project=stg

      - name: Upload STG HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: STG-Playwright-Report
          path: playwright-report/

  deploy:
    name: Deploy to PROD
    needs: stg-test
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Deployment
        run: |
          echo "=========================="
          echo "Deploying to Production..."
          echo "Deployment Successful"
          echo "=========================="

  prod-test:
    name: PROD Tests
    needs: deploy
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run PROD Tests
        run: npx playwright test tests/login.spec.ts --project=prod

      - name: Upload PROD HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PROD-Playwright-Report
          path: playwright-report/