name: Playwright STG PROD Pipeline

on:
  workflow_dispatch:

jobs:
  stg-test:
    name: STG Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run STG Tests
        run: npx playwright test tests/login.spec.ts --project=stg

      - name: Upload STG Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: STG-Playwright-Report
          path: playwright-report/

  deploy:
    name: Deploy to Production
    needs: stg-test
    if: needs.stg-test.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Deployment
        run: |
          echo "================================"
          echo "Deploying to Production..."
          sleep 5
          echo "Deployment Successful"
          echo "================================"

  prod-test:
    name: PROD Tests
    needs: deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run PROD Tests
        run: npx playwright test tests/login.spec.ts --project=prod

      - name: Upload PROD Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PROD-Playwright-Report
          path: playwright-report/
          

            email-on-failure:
    if: failure()
    needs: [stg-test, deploy, prod-test]
    runs-on: ubuntu-latest

    steps:
      - name: Send Failure Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "❌ Playwright Pipeline Failed"

          to: yourgmail@gmail.com

          from: GitHub Actions

          body: |
            Playwright Pipeline Failed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}

            Workflow:
            ${{ github.workflow }}

            Run Link:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}